### ISSUE TITLE
PART TWO - IMPORT DATA INTO FIREBASE

### ISSUE THREAD

**Issue by GitEbachS** [nss-evening-cohort-24/pos-system-the-ronis#16]
#User Story
I, the user, will need to be able manipulate data on the app. Firebase is useful in storing my personal data (objects with its attributes) related to my orders.  

#Dependencies
Firebase data import is dependent upon the mockaroo data being setup, imported via json file into my util > sample_data > .js file. All of the users' "uids" needs to be added to the data in VS Code for testing multiple users. 
Then, this data can be imported in Firebase Realtime Data as a JSON file.

The Rules should reflect the fetch calls required.

**Comment by keanacobarde** [comment]
Imported Orders and Items data into FireBase. Testing with Postman was successful. Closing issue.
