### ISSUE TITLE
PART TWO - VIEW ALL ORDERS, CREATE AN ORDER

### ISSUE THREAD

**Issue by GitEbachS** [nss-evening-cohort-24/pos-system-the-ronis#17]
#User Story
On the first page under my account name, I, the user, should see a header tag with my name. The View Orders, Create an Order, and View Revenue buttons should be in a single column. 

#Dependencies
The first user page with the 3 buttons will depend upon the login auth, and the following code will depend upon the data being tested in Postman and imported into Firebase.

#Dev Notes
Promises in api to code:

- [x] getOrder  > method: 'GET'

Other functions to code:
#1 showOrders (cards on dom) :

- [x] pages > orders.js
- [x] provide an emptyOrders() globally, with a domString that states that there are no orders created, yet!
- [x] inside the showOrders(), call clearDom()
- [x] then, if !array.length, call emptyOrders(); else, use the array.forEach loop for the domString card to be displayed
- [x] - [ ] renderToDom() > #main-container

#2 addOrderForm with the 'uid' being passed as a parameter (form card from Bootstrap):

- [x] forms > addOrderForm.js
- [x] include clearDom() first, then the form card domString to render
- [x] renderToDom() > #form-container

When the View Orders button is clicked,
Example code for button:

![Image](https://user-images.githubusercontent.com/119310701/266885148-ebea82d5-11ca-48ce-81d0-bcb4e2bd3686.png)

The event listener will target the View Orders button id, and getOrders(user.uid) gets called. Then, that array gets passed in the showOrders function (which will put the order cards on the DOM).
Example code for event listener:

![Image](https://user-images.githubusercontent.com/119310701/266886208-c887486b-39a2-4cbb-9915-648266f4c760.png)

When the Create Orders button is clicked, the event listener, in domEvents.js, will target the Create Orders button id (example: 'add-order-btn'), and the addOrderForm(user.uid) function gets called. Example from another project, below:

![Image](https://user-images.githubusercontent.com/119310701/266888726-82bd1db2-2906-4a88-a541-5dc6dd2b7c3f.png)

The form data being captured will be on the next issue ticket.

**Comment by keanacobarde** [comment]
Closed, per application meets accepted criteria.
