### ISSUE TITLE
PART TWO - DETAILS BUTTON > VIEW ITEMS AND PRICE

### ISSUE THREAD

**Issue by GitEbachS** [nss-evening-cohort-24/pos-system-the-ronis#19]
#User Story
I, the user, may have a huge family that likes to eat a lot of food. No problem. I can click the 'Details' button on my order card, and I can see a list of all the yummy pizza and wing food choices to purchase. The 'add item' button allows me to add as much food as my family needs to have happy, full tummies.  
When I first see the 'add items' page, it should be empty with a domString that says something like, "Your tummy is growling! Please select your items you wish to purchase!"
Then, the 'Add Item' button allows me to add my food items, to my item list page, by selecting (probably via dropdown) a food on my items and price form. I can click the links: 'Edit Item' or 'Delete Item' on my list items page as well. The price of the total items should be displayed at the top of the page. Once I have added everything, I can click the 'Go To Payment' button to checkout, and pay for the order created.

#Dependencies
This is dependent on the getOrders, createOrders, updateOrders, deleteOrders, getSingleOrders promises being coded and displayed in the api folder and in the orderData.js file. 

#Dev Notes
There will need to be a div container for 'ordered-items' in the domBuilder.js. 
The renderToDom will send the itemCard domString to this container (page).

When the 'Details' button is clicked on the Order card:
The event listener will target the button's id, and the firebaseKey of that order. It will then get the array of items from that object, and display them in a bootstrap card. Example from another project below:

![Image](https://user-images.githubusercontent.com/119310701/266899501-37742df9-1fae-4b3b-b4e0-018a6ec2fdc7.png)

Another example for this project for the event Listener would look something like this:
getSingleOrder(firebaseKey).then((order) => order.items).then(showItems(array))

The showItems(array) would be the card on dom for the list of items. Notes about this function:
- [ ] pages > showItems.js
- [ ] clearDom()
- [ ] forEach loop needed
- [ ] renderToDom > #ordered-items div

**Comment by keanacobarde** [comment]
Done - all items associated with specific orders can be viewed and modified. Primary issues were: 
- Specificity of propery access [details.orderItems] 
- Created merged API calls after orderItems table creation. 
If an order does NOT have any items associated with it, the 'add item' button can be selected.
