### ISSUE TITLE
PART FOUR- ADD ITEM FORM

### ISSUE THREAD

**Issue by GitEbachS** [nss-evening-cohort-24/pos-system-the-ronis#20]
#User Story
Same as the previous ticket #19.

#Dependencies
The itemForm needs to be created and placed in a div container in the domBuilder.js. 
Promises that need to be completed: getSingleItem(firebaseKey), createItem(payload), updateItem(patchPayload), 
Promises location: api > itemsData.js

When the 'Add Item' button is clicked on the list items page, the event listener targets button id. Then, the addItemForm() is returned.
The form has two values:
Item Name (dropdown, possibly)
Item Price (matches with the item name)

Next, the form event listener would target the id on itemForm id 'add-item' or 'update-item' (if firebaseKey is present). 
For 'add-item', when 'submit' is clicked:
There would be a new payload with: { item name, item price, uid: user.uid }
 Then, createItems(payload).then(({ name })) =>
    const patchPayload = { firebaseKey: name };
     updateItem(patchPayLoad).then(() => 
      getSingleOrder(firebaseKey).then((order) => order.items.then(showItems(array))

For the 'update-item', when 'submit' is clicked:
This would be the example:

![Image](https://user-images.githubusercontent.com/119310701/266908106-d02b0a9b-1bce-4c9e-9146-7a73ccf6217a.png)

**Comment by keanacobarde** [comment]
Accepted criteria is met through functionality introduced in merged branches. Closing ticket.
